### PR TITLE
Show All Projects

### PR DESCRIPTION
**Pull request by denrase**
# Context & Problem

We get many negative reviews that their projects are not showing up in the app. This was due to the fact that we decided to only show projects with session data.

# Solution

- We now show all projects, not just the ones with session data.
- The ones without session data link to `https://docs.sentry.io/product/releases/health/`

# Assets

Simulator Screen Shot - iPhone 13 Pro - 2021-12-14 at 15 36 02

Simulator Screen Shot - iPhone 13 Pro - 2021-12-14 at 15 36 53

### CODE REVIEW

**Comment by marandaneto** [comment]
I'd rather have a toggle for showing all projects (or hide projects without release health data), otherwise either you know by heart which projects have release health data or you have to go 1 by 1 every time.

**Comment by denrase** [comment]
Hmm, yeah the issues is that the first launch experience for users without sessions is really bad, so this should be an opt out. I'd also guess that most users don't have as many projects as we do? 
You can always fave projects to show them at the front of the list. My concern is that this will get too complicated if we add even more options? 🤔

**Comment by denrase** [comment]
@HazAT @bruno-garcia Any thoughts/feedback regarding this?

**Comment by bruno-garcia** [comment]
Lets make sure the order we display are: Projects with Session data followed by projects without session data. Other than that LGTM!

**Comment by denrase** [comment]
@bruno-garcia It's sorted now. Although theres still a small issue, as the API call is reporting that some projects have sessions, but when fetching individually there is no session data.

**Review by bruno-garcia — APPROVED** [review]

**Comment by bruno-garcia** [comment]
thanks Denis

**Comment by marandaneto** [comment]
> @bruno-garcia It's sorted now. Although theres still a small issue, as the API call is reporting that some projects have sessions, but when fetching individually there is no session data.

@bruno-garcia @denrase should we open an issue about that on https://github.com/getsentry/sentry?

**Pull request merged**
