### PR TITLE
feat: Send event and message from debug screen

### PR DESCRIPTION
**Pull request by denrase**
# Overview

- Add 'Sentry.captureEvent' and 'Sentry.captureMessage' to debug screen

# Testing

When testing the behaviour of the SDK in relation to #155, following things were uncovered:

- Diable and Re-Enable SDK
    - `Sentry.captureException`: The captured errors are reported multiple times to sentry if the SDK is diabled/enabled multiple times within the app. This could not be reproduced for 'Sentry.captureEvent', 'Sentry.captureMessage' and capturing of crashes in native code (iOS).
-  Disable Enabled SDK
    - Native crashes were sent after SDK was disabled within the app. Of course, had to enable it after the app crashed to give the SDK a chance to upload, but they should not have been captured during disabled phase in the first place.

@marandaneto How should we best proceed here in regards to the SDK?

# Assets

Simulator Screen Shot - iPhone 12 Pro - 2021-03-08 at 13 08 37

### CODE REVIEW

**Comment by marandaneto** [comment]
> Native crashes were sent after SDK was disabled within the app. Of course, had to enable it after the app crashed to give the SDK a chance to upload, but they should not have been captured during disabled phase in the first place.

this was already known and tracked by https://github.com/getsentry/sentry-dart/issues/291

**Comment by marandaneto** [comment]
> The captured errors are reported multiple times to sentry if the SDK is diabled/enabled multiple times within the app. This could not be reproduced for 'Sentry.captureEvent', 'Sentry.captureMessage' and capturing of crashes in native code (iOS).

I'm not sure if I understood the problem here, you enable SDK, disable SDK, re-enable SDK and call `captureException` and the same exception were captured multiple times?

I'm wondering if this could be because we register the `runZonedGuarded` or the `Isolate.current` and they chain the exception multiple times? could you check this out?

I don't think it's related to the `FlutterError.onError` because it's a static/single value thing.

I believe release health was not tested, right?

**Comment by denrase** [comment]
```
I'm not sure if I understood the problem here, you enable SDK, disable SDK, re-enable SDK and call captureException and the same exception were captured multiple times?
```

Yes, this is the behaviour I'm was seeing. Will double check.

We only do a custom `runZonedGuarded` around application creation in `main.dart` once, this is not done again during runtime when enabling/disabling the SDK. Not doint anything explicit in the app with `Isolate.current`. 

As for release health, how would i best test his? Check if errored sessions show up in the graph data?

**Comment by denrase** [comment]
@marandaneto Think I found the reason.

In the `FlutterErrorIntegration`, we are referencing the previous `FlutterError.onError` function within the newly created one with `defaultOnError`. So we are essentially building a chain back to every time a new `FlutterErrorIntegration` is initialized. That's why it is reported multiple times.

Maybe we can check wether the previous function was set by our SDK, and if so, don't call it. Or hold the reference to the default ourselves, instead of always reading it from `FlutterError.onError` every time.

Bildschirmfoto 2021-03-08 um 14 11 37
Bildschirmfoto 2021-03-08 um 14 03 09

**Comment by denrase** [comment]
@marandaneto As far as release health goes, we are using the sessions API for the presented data in the app. I am seeing healthy, errored and crashed sessions for `sentry-mobile-development` project. Did not count the number of sessions myself though to match if every one is there, but the graph looks reasonable as there are many errored/crashed sessions and thats what i was testing today. Is there any other metric i could check?

Simulator Screen Shot - iPhone 12 Pro - 2021-03-08 at 14 30 43

**Comment by marandaneto** [comment]
> @marandaneto Think I found the reason.
> 
> In the `FlutterErrorIntegration`, we are referencing the previous `FlutterError.onError` function within the newly created one with `defaultOnError`. So we are essentially building a chain back to every time a new `FlutterErrorIntegration` is initialized. That's why it is reported multiple times.
> 
> Maybe we can check wether the previous function was set by our SDK, and if so, don't call it. Or hold the reference to the default ourselves, instead of reading it from `FlutterError.onError` every time.
> 
> Bildschirmfoto 2021-03-08 um 14 11 37
> 
> Bildschirmfoto 2021-03-08 um 14 03 09

that makes total sense, either we check if its ours or if its the Flutter default one, good catch

**Comment by marandaneto** [comment]
> @marandaneto As far as release health goes, we are using the sessions API for the presented data in the app. I am seeing healthy, errored and crashed sessions for `sentry-mobile-development` project. Did not count the number of sessions myself though to match if every one is there, but the graph looks reasonable as there are many errored/crashed sessions and thats what i was testing today. Is there any other metric i could check?
> 
> Simulator Screen Shot - iPhone 12 Pro - 2021-03-08 at 14 30 43

we'd need to count the sessions here, it's the only way.
we start a session when the activity is in the foreground, if the SDK is disabled at this moment, no session "start" is sent to sentry, hence the counts are gonna be wrong.
if you enable the SDK, put the app to background, and back to foreground, it should adjust itself.

**Pull request merged**
